"""
RSS Feed Generator — Makes the dossier discoverable via RSS readers and aggregators.

Generates docs/feed.xml (Atom 2.0) from historical dossier summary files.
RSS feeds are how content gets discovered by:
  - RSS readers (Feedly, Inoreader, etc)
  - News aggregators
  - SEO crawlers (Google indexes RSS feeds!)
  - Other AI agents consuming financial content

Usage (called by generate.py):
    from dossier.report.rss_feed import generate_rss_feed
    generate_rss_feed()
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom.minidom import parseString

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
API_DIR = PROJECT_ROOT / "docs" / "api"
OUTPUT_PATH = PROJECT_ROOT / "docs" / "feed.xml"

SITE_URL = "https://mphinance.github.io/mphinance"
FEED_TITLE = "Ghost Alpha Dossier — Daily Market Intelligence"
FEED_DESCRIPTION = (
    "AI-powered daily market analysis with institutional-grade signals, "
    "momentum picks, and Sam's commentary. Generated by a 16-stage pipeline. "
    "Built by Michael. Roasted by Sam."
)


def generate_rss_feed(max_entries: int = 30) -> str:
    """
    Generate an RSS 2.0 feed from historical dossier summaries.
    Returns the XML string.
    """
    print("  Generating RSS feed...")

    # Collect all dossier summaries
    summaries = []
    for api_file in sorted(API_DIR.glob("dossier-2*.json"), reverse=True):
        try:
            with open(api_file) as f:
                summary = json.load(f)
            summaries.append(summary)
            if len(summaries) >= max_entries:
                break
        except Exception:
            continue

    if not summaries:
        print("  [WARN] No dossier summaries found for RSS feed")
        return ""

    # Build RSS XML
    rss = Element("rss", version="2.0")
    rss.set("xmlns:atom", "http://www.w3.org/2005/Atom")

    channel = SubElement(rss, "channel")
    SubElement(channel, "title").text = FEED_TITLE
    SubElement(channel, "link").text = SITE_URL
    SubElement(channel, "description").text = FEED_DESCRIPTION
    SubElement(channel, "language").text = "en-us"
    SubElement(channel, "lastBuildDate").text = datetime.now(timezone.utc).strftime(
        "%a, %d %b %Y %H:%M:%S +0000"
    )

    # Self-referencing link for RSS readers
    atom_link = SubElement(channel, "atom:link")
    atom_link.set("href", f"{SITE_URL}/feed.xml")
    atom_link.set("rel", "self")
    atom_link.set("type", "application/rss+xml")

    # Generator tag
    SubElement(channel, "generator").text = "Ghost Alpha Pipeline v2.0"

    for summary in summaries:
        meta = summary.get("meta", {})
        market = summary.get("market", {})
        picks = summary.get("picks", {})
        signals = summary.get("signals", {})
        sam = summary.get("sam", {})
        narrative = summary.get("narrative", {})

        date = meta.get("date", "")
        report_url = meta.get("report_url", "")

        # Build item title
        gold = picks.get("gold")
        regime = market.get("regime", "Unknown")
        regime_emoji = market.get("regime_emoji", "")
        vix = market.get("vix", 0)

        title = f"{regime_emoji} Dossier {date} — {regime}"
        if gold:
            title += f" · Gold: {gold['ticker']}"

        # Build item description (HTML)
        spy = market.get("spy", {})
        spy_chg = spy.get("change_pct", 0)
        spy_dir = "▲" if spy_chg >= 0 else "▼"
        signal_count = signals.get("count", 0)

        desc_parts = [
            f"<p><strong>{regime_emoji} {regime}</strong> · SPY {spy_dir} {abs(spy_chg):.1f}% · VIX {vix:.1f}</p>",
        ]

        if narrative.get("one_liner"):
            desc_parts.append(f"<p>{narrative['one_liner']}</p>")

        if gold:
            desc_parts.append(
                f"<p>🥇 <strong>Gold Pick: {gold['ticker']}</strong> — "
                f"Score: {gold.get('score', 0)}/100 ({gold.get('grade', '')})</p>"
            )

        desc_parts.append(f"<p>📡 {signal_count} scanner signals across 6 strategies</p>")

        if sam.get("quote"):
            desc_parts.append(f"<blockquote><em>\"{sam['quote']}\"</em> — Sam</blockquote>")

        description = "\n".join(desc_parts)

        # Build the RSS item
        item = SubElement(channel, "item")
        SubElement(item, "title").text = title
        SubElement(item, "link").text = report_url
        SubElement(item, "description").text = description

        # Use the date as GUID
        SubElement(item, "guid", isPermaLink="false").text = f"dossier-{date}"

        # Pub date
        try:
            dt = datetime.strptime(date, "%Y-%m-%d")
            SubElement(item, "pubDate").text = dt.strftime(
                "%a, %d %b %Y 06:00:00 +0000"  # 6AM UTC = 5AM CST pipeline
            )
        except Exception:
            pass

    # Pretty-print the XML
    rough_string = tostring(rss, encoding="unicode")
    xml_string = parseString(rough_string).toprettyxml(indent="  ", encoding=None)

    # Remove the XML declaration (we'll add our own)
    lines = xml_string.split("\n")
    if lines[0].startswith("<?xml"):
        lines = lines[1:]
    xml_body = "\n".join(lines)

    full_xml = '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_body

    # Write to disk
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(full_xml)

    print(f"  ✓ RSS feed: {OUTPUT_PATH} ({len(summaries)} entries)")
    return full_xml


if __name__ == "__main__":
    generate_rss_feed()
